"""add slug field to departments

Revision ID: b82c9f05a24d
Revises: b84f4145a2c2
Create Date: 2026-03-21 16:41:36.553879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82c9f05a24d'
down_revision: Union[str, Sequence[str], None] = 'b84f4145a2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_departments_slug'), 'departments', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_slug'), table_name='departments')
    op.drop_column('departments', 'slug')
    # ### end Alembic commands ###
