"""initial tables

Revision ID: f1b3f0521a1d
Revises: 480b3b6cbecc
Create Date: 2026-03-18 17:48:37.239921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1b3f0521a1d'
down_revision: Union[str, Sequence[str], None] = '480b3b6cbecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_context_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_context_category', 'document_context_chunks', ['category'], unique=False)
    op.create_index('idx_doc_context_subcategory', 'document_context_chunks', ['subcategory'], unique=False)
    op.create_index(op.f('ix_document_context_chunks_category'), 'document_context_chunks', ['category'], unique=False)
    op.create_index(op.f('ix_document_context_chunks_chunk_hash'), 'document_context_chunks', ['chunk_hash'], unique=True)
    op.create_index(op.f('ix_document_context_chunks_subcategory'), 'document_context_chunks', ['subcategory'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('PUMP', 'SOLAR_PANEL', 'INVERTER', 'CONTROLLER', 'TANK', 'PIPE', 'FITTING', 'FILTER', 'TREATMENT', 'ELECTRICAL', 'ACCESSORY', name='equipmentcategory'), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('bc_item_no', sa.String(length=100), nullable=True),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bc_item_no'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_bc_item_no', 'equipment', ['bc_item_no'], unique=False)
    op.create_index('idx_category', 'equipment', ['category'], unique=False)
    op.create_index('idx_equipment_is_active', 'equipment', ['is_active'], unique=False)
    op.create_index('idx_sku', 'equipment', ['sku'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SALES_ENGINEER', 'MANAGER', 'TECHNICIAN', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.create_index('idx_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_role', 'users', ['role'], unique=False)
    op.create_table('workflow_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.String(length=50), nullable=True),
    sa.Column('workflow_type', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('agent_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('total_execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stage', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_logs_workflow_id'), 'workflow_logs', ['workflow_id'], unique=False)
    op.create_table('workflow_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trace_workflow_time', 'workflow_traces', ['workflow_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workflow_traces_created_at'), 'workflow_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_traces_user_email'), 'workflow_traces', ['user_email'], unique=False)
    op.create_index(op.f('ix_workflow_traces_workflow_id'), 'workflow_traces', ['workflow_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_no', sa.String(length=50), nullable=False),
    sa.Column('bc_customer_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('customer_type', sa.Enum('RETAIL', 'CONTRACTOR', 'GOVERNMENT', 'NGO', 'CORPORATE', 'DISTRIBUTOR', name='customertype'), nullable=False),
    sa.Column('credit_limit', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('sales_representative_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sales_representative_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_no')
    )
    op.create_index('idx_customer_no', 'customers', ['customer_no'], unique=False)
    op.create_index('idx_customer_type', 'customers', ['customer_type'], unique=False)
    op.create_index('idx_name', 'customers', ['name'], unique=False)
    op.create_index('idx_sales_representative_id', 'customers', ['sales_representative_id'], unique=False)
    op.create_table('pump_curves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('hq_coef_a', sa.Float(), nullable=False),
    sa.Column('hq_coef_b', sa.Float(), nullable=False),
    sa.Column('hq_coef_c', sa.Float(), nullable=False),
    sa.Column('eff_coef_a', sa.Float(), nullable=True),
    sa.Column('eff_coef_b', sa.Float(), nullable=True),
    sa.Column('eff_coef_c', sa.Float(), nullable=True),
    sa.Column('power_coef_a', sa.Float(), nullable=True),
    sa.Column('power_coef_b', sa.Float(), nullable=True),
    sa.Column('power_coef_c', sa.Float(), nullable=True),
    sa.Column('min_flow', sa.Float(), nullable=False),
    sa.Column('max_flow', sa.Float(), nullable=False),
    sa.Column('impeller_diameter_mm', sa.Float(), nullable=True),
    sa.Column('speed_rpm', sa.Integer(), nullable=True),
    sa.Column('hq_r_squared', sa.Float(), nullable=True),
    sa.Column('eff_r_squared', sa.Float(), nullable=True),
    sa.Column('power_r_squared', sa.Float(), nullable=True),
    sa.Column('raw_curve_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pump_curves_equipment_id'), 'pump_curves', ['equipment_id'], unique=False)
    op.create_table('pumps',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('motor_power_kw', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('max_flow_rate', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('max_head', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('voltage_ac', sa.Integer(), nullable=True),
    sa.Column('phase_type', sa.String(length=20), nullable=True),
    sa.Column('performance_curve_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('solar_panels',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('rated_power_wp', sa.Integer(), nullable=False),
    sa.Column('voc', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('vmp', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('efficiency', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('cell_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('idayliff_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('pump_model', sa.String(length=255), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INSTALLED', 'ACTIVE', 'MAINTENANCE', 'INACTIVE', 'DECOMMISSIONED', name='installationstatus'), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('total_running_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_no')
    )
    op.create_index('idx_install_customer_id', 'idayliff_installations', ['customer_id'], unique=False)
    op.create_index('idx_install_equipment_id', 'idayliff_installations', ['equipment_id'], unique=False)
    op.create_index('idx_installation_no', 'idayliff_installations', ['installation_no'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_number', sa.String(length=50), nullable=False),
    sa.Column('inquiry_type', sa.Enum('PUMP_SIZING', 'WATER_TREATMENT', 'SOLAR_PUMPING', 'IRRIGATION', 'GENERATOR', 'GENERAL', name='inquirytype'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('site_location', sa.Text(), nullable=True),
    sa.Column('inquiry_status', sa.Enum('NEW', 'IN_PROGRESS', 'DESIGN_COMPLETE', 'QUOTED', 'WON', 'LOST', 'ON_HOLD', name='inquirystatus'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='prioritylevel'), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_number')
    )
    op.create_index('idx_assigned_to', 'inquiries', ['assigned_to'], unique=False)
    op.create_index('idx_customer_id', 'inquiries', ['customer_id'], unique=False)
    op.create_index('idx_inquiry_number', 'inquiries', ['inquiry_number'], unique=False)
    op.create_index('idx_inquiry_status', 'inquiries', ['inquiry_status'], unique=False)
    op.create_index('idx_inquiry_type', 'inquiries', ['inquiry_type'], unique=False)
    op.create_table('idayliff_alarms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('alarm_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['installation_id'], ['idayliff_installations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alarm_installation_id', 'idayliff_alarms', ['installation_id'], unique=False)
    op.create_index('idx_resolved', 'idayliff_alarms', ['resolved'], unique=False)
    op.create_table('idayliff_telemetry_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('flow_rate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('pressure', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('power_consumption', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('temperature', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('vibration', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['installation_id'], ['idayliff_installations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_installation_id', 'idayliff_telemetry_history', ['installation_id'], unique=False)
    op.create_index('idx_timestamp', 'idayliff_telemetry_history', ['timestamp'], unique=False)
    op.create_table('lab_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('sampling_date', sa.Date(), nullable=False),
    sa.Column('water_source', sa.String(length=255), nullable=False),
    sa.Column('site_location', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('minio_bucket', sa.String(length=100), nullable=True),
    sa.Column('minio_object_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no')
    )
    op.create_index('idx_lab_customer_id', 'lab_reports', ['customer_id'], unique=False)
    op.create_index('idx_lab_inquiry_id', 'lab_reports', ['inquiry_id'], unique=False)
    op.create_index('idx_reference_no', 'lab_reports', ['reference_no'], unique=False)
    op.create_table('site_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('water_source', sa.String(length=100), nullable=True),
    sa.Column('depth_to_water', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('power_source', sa.String(length=50), nullable=True),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_site_inquiry_id', 'site_assessments', ['inquiry_id'], unique=False)
    op.create_table('solar_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('water_source_type', sa.String(length=50), nullable=False),
    sa.Column('static_water_level', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('well_depth', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('daily_water_requirement', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('peak_sun_hours', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('delivery_distance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('storage_capacity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_solar_inquiry_id', 'solar_assessments', ['inquiry_id'], unique=False)
    op.create_table('system_designs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('design_number', sa.String(length=50), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('design_status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'REVISED', name='designstatus'), nullable=True),
    sa.Column('total_dynamic_head', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('required_flow_rate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('motor_input_power_kw', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ai_confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ai_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_number')
    )
    op.create_table('quotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('system_design_id', sa.UUID(), nullable=True),
    sa.Column('quotation_title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'REVISED', name='quotationstatus'), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('valid_until_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.ForeignKeyConstraint(['system_design_id'], ['system_designs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_number')
    )
    op.create_index('idx_quotation_number', 'quotations', ['quotation_number'], unique=False)
    op.create_index('idx_quote_customer_id', 'quotations', ['customer_id'], unique=False)
    op.create_index('idx_quote_inquiry_id', 'quotations', ['inquiry_id'], unique=False)
    op.create_index('idx_status', 'quotations', ['status'], unique=False)
    op.create_table('water_quality_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lab_report_id', sa.UUID(), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('who_guideline', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['lab_report_id'], ['lab_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lab_report_id', 'water_quality_parameters', ['lab_report_id'], unique=False)
    op.create_index('idx_parameter_name', 'water_quality_parameters', ['parameter_name'], unique=False)
    op.create_table('water_treatment_workflow_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lab_report_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.String(length=80), nullable=False),
    sa.Column('primary_process', sa.String(length=20), nullable=True),
    sa.Column('permeate_output_m3_hr', sa.Float(), nullable=True),
    sa.Column('treatment_design', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_report_id'], ['lab_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wt_workflow_lab', 'water_treatment_workflow_results', ['lab_report_id', 'workflow_id'], unique=False)
    op.create_index(op.f('ix_water_treatment_workflow_results_lab_report_id'), 'water_treatment_workflow_results', ['lab_report_id'], unique=False)
    op.create_index(op.f('ix_water_treatment_workflow_results_workflow_id'), 'water_treatment_workflow_results', ['workflow_id'], unique=False)
    op.create_table('quotation_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('item_category', sa.Enum('EQUIPMENT', 'INSTALLATION', 'CIVIL_WORKS', 'ELECTRICAL', 'COMMISSIONING', 'TRANSPORT', 'WARRANTY', 'SERVICE', name='itemcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_equipment_id', 'quotation_line_items', ['equipment_id'], unique=False)
    op.create_index('idx_quotation_id', 'quotation_line_items', ['quotation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_quotation_id', table_name='quotation_line_items')
    op.drop_index('idx_equipment_id', table_name='quotation_line_items')
    op.drop_table('quotation_line_items')
    op.drop_index(op.f('ix_water_treatment_workflow_results_workflow_id'), table_name='water_treatment_workflow_results')
    op.drop_index(op.f('ix_water_treatment_workflow_results_lab_report_id'), table_name='water_treatment_workflow_results')
    op.drop_index('idx_wt_workflow_lab', table_name='water_treatment_workflow_results')
    op.drop_table('water_treatment_workflow_results')
    op.drop_index('idx_parameter_name', table_name='water_quality_parameters')
    op.drop_index('idx_lab_report_id', table_name='water_quality_parameters')
    op.drop_table('water_quality_parameters')
    op.drop_index('idx_status', table_name='quotations')
    op.drop_index('idx_quote_inquiry_id', table_name='quotations')
    op.drop_index('idx_quote_customer_id', table_name='quotations')
    op.drop_index('idx_quotation_number', table_name='quotations')
    op.drop_table('quotations')
    op.drop_table('system_designs')
    op.drop_index('idx_solar_inquiry_id', table_name='solar_assessments')
    op.drop_table('solar_assessments')
    op.drop_index('idx_site_inquiry_id', table_name='site_assessments')
    op.drop_table('site_assessments')
    op.drop_index('idx_reference_no', table_name='lab_reports')
    op.drop_index('idx_lab_inquiry_id', table_name='lab_reports')
    op.drop_index('idx_lab_customer_id', table_name='lab_reports')
    op.drop_table('lab_reports')
    op.drop_index('idx_timestamp', table_name='idayliff_telemetry_history')
    op.drop_index('idx_telemetry_installation_id', table_name='idayliff_telemetry_history')
    op.drop_table('idayliff_telemetry_history')
    op.drop_index('idx_resolved', table_name='idayliff_alarms')
    op.drop_index('idx_alarm_installation_id', table_name='idayliff_alarms')
    op.drop_table('idayliff_alarms')
    op.drop_index('idx_inquiry_type', table_name='inquiries')
    op.drop_index('idx_inquiry_status', table_name='inquiries')
    op.drop_index('idx_inquiry_number', table_name='inquiries')
    op.drop_index('idx_customer_id', table_name='inquiries')
    op.drop_index('idx_assigned_to', table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index('idx_installation_no', table_name='idayliff_installations')
    op.drop_index('idx_install_equipment_id', table_name='idayliff_installations')
    op.drop_index('idx_install_customer_id', table_name='idayliff_installations')
    op.drop_table('idayliff_installations')
    op.drop_table('solar_panels')
    op.drop_table('pumps')
    op.drop_index(op.f('ix_pump_curves_equipment_id'), table_name='pump_curves')
    op.drop_table('pump_curves')
    op.drop_index('idx_sales_representative_id', table_name='customers')
    op.drop_index('idx_name', table_name='customers')
    op.drop_index('idx_customer_type', table_name='customers')
    op.drop_index('idx_customer_no', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_workflow_traces_workflow_id'), table_name='workflow_traces')
    op.drop_index(op.f('ix_workflow_traces_user_email'), table_name='workflow_traces')
    op.drop_index(op.f('ix_workflow_traces_created_at'), table_name='workflow_traces')
    op.drop_index('idx_trace_workflow_time', table_name='workflow_traces')
    op.drop_table('workflow_traces')
    op.drop_index(op.f('ix_workflow_logs_workflow_id'), table_name='workflow_logs')
    op.drop_table('workflow_logs')
    op.drop_index('idx_role', table_name='users')
    op.drop_index('idx_is_active', table_name='users')
    op.drop_index('idx_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_sku', table_name='equipment')
    op.drop_index('idx_equipment_is_active', table_name='equipment')
    op.drop_index('idx_category', table_name='equipment')
    op.drop_index('idx_bc_item_no', table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_document_context_chunks_subcategory'), table_name='document_context_chunks')
    op.drop_index(op.f('ix_document_context_chunks_chunk_hash'), table_name='document_context_chunks')
    op.drop_index(op.f('ix_document_context_chunks_category'), table_name='document_context_chunks')
    op.drop_index('idx_doc_context_subcategory', table_name='document_context_chunks')
    op.drop_index('idx_doc_context_category', table_name='document_context_chunks')
    op.drop_table('document_context_chunks')
    # ### end Alembic commands ###
